server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mohamed-Arshad/Spring-Cloud-Config-Store
          search-paths:
           - '*service'



